- id: "1661001660553"
  alias: zone_enter
  description: ""
  trigger:
    - platform: device
      device_id: 7cdfa2077afc12c1ae5857804fd1bd81
      domain: device_tracker
      entity_id: device_tracker.sunnys_iphone_2
      type: enters
      zone: zone.home
  condition: []
  action:
    - service: tts.google_say
      entity_id:
        - media_player.isabella_speaker
      data_template:
        message: " Welcome home sunny"
  mode: single

- id: "1661001752257"
  alias: zone_leave
  description: ""
  trigger:
    - platform: device
      device_id: 7cdfa2077afc12c1ae5857804fd1bd81
      domain: device_tracker
      entity_id: device_tracker.sunnys_iphone_2
      type: leaves
      zone: zone.home
  condition: []
  action:
    - service: tts.google_say
      entity_id:
        - media_player.isabella_speaker
      data_template:
        message: Goodbye sunny
