# Root configuration for home assistant
# Secrets are defined in the file secrets.yaml

homeassistant:
  # Name of the location where Home Assistant is running
  name: Bäckebolsängen
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 10
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization files
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  # No login for watch/phone, see https://www.home-assistant.io/docs/authentication/provider
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 127.0.0.1
        - ::1
      allow_bypass_login: true

hassio:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Support person component
person:

automation: !include automations.yaml

# System health info support
system_health:

# WOL for SpelTV
# wake_on_lan:

# Allow mobile companion apps
#mobile_app:

samsungtv:
  - host: 192.168.1.127

hacs:
  token: !secret github_personal_access_token

# Track device location with nmap. See secrets.yaml for gpslogger configuration.
#device_tracker:
#  - platform: nmap_tracker
#    hosts:
#      - 192.168.1.162
#    home_interval: 5
#    consider_home: 180

# Example configuration.yaml entry
#notify:

#   - name: email
#     platform: sendgrid
#     api_key: !secret sendgrid_api_key
#     sender: !secret sender_email_address
#     recipient: !secret recipient_email_address

mobile_app:

# Lovelace UI
lovelace:
  #mode: yaml #If wanted to edit dashboard manually, just comment this section
  resources:
    # https://github.com/thomasloven/lovelace-auto-entities/
    - url: /local/auto-entities.js
      type: module
    # https://github.com/bramkragten/weather-card
    - url: /local/weather-card.js
      type: module
    # https://github.com/thomasloven/lovelace-layout-card
    - url: /local/layout-card.js
      type: module
    # https://github.com/Villhellm/lovelace-animated-background
    - url: /local/animated-background.js
      type: module

    - url: /local/weatherbg-card.js
      type: module

    # - url: /local/mini-media-player-bundle.js
    #   type: module

    # - url: /local/vasttrafik-card.js
    #   type: module

    - url: /local/card-tools.js
      type: module

tts:
  - platform: google_translate
    language: en
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: http://192.168.1.122:8123
    service_name: google_say

sensor:
  - platform: vasttrafik
    key: !secret vasttrafik_key
    secret: !secret vasttrafik_secret
    departures:
      - from: Akkas Gata, Göteborg
        heading: Hjalmar Brantingsplatsen, Göteborg
        name: 18, Akkas Gata to Johanneberg
        lines:
          - 18
        delay: 5
      - from: Akkas Gata, Göteborg
        heading: Hjalmar Brantingsplatsen, Göteborg
        name: 19, Akkas Gata to Fredriksdal
        lines:
          - 19
        delay: 5
      - from: Friedländers Gata, Göteborg
        heading: Angered Centrum, Göteborg
        name: 40, Friedländers Gata to Angered Centrum
        lines:
          - 40
        delay: 5
      - from: Friedländers Gata, Göteborg
        heading: Hjalmar Brantingsplatsen, Göteborg
        name: 40, Friedländers Gata to Hjalmar Brantingsplatsen
        lines:
          - 40
        delay: 5
      - from: Akkas Gata, Göteborg
        heading: Marklandsgatan, Göteborg
        name: 45, Akkas Gata to Marklandsgatan
        lines:
          - 45

  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "date_time_iso"
      - "time_date"
      - "time_utc"
      - "beat"

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_secret

# Raspberrypi surveillance camera
camera:
  - platform: ffmpeg
    name: RasPi4
    input: rtsp://192.168.1.76:8554/unicast

# Allow proxy/reverse-proxy requests from cloudflare add-on to the HA
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
