# Root configuration for Home Assistant
# Secrets are defined in the file secrets.yaml

homeassistant:
  name: Bäckebolsängen
  elevation: 10
  unit_system: metric
  time_zone: Europe/Stockholm
  allowlist_external_dirs:
    - /config/www
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 127.0.0.1
        - ::1
      allow_bypass_login: true

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 16
    icon: mdi:home

# Core integrations
frontend:
  themes: !include_dir_merge_named themes

config:

conversation:

history:

logbook:

sun:

person:

automation: !include automations.yaml

system_health:

# Devices and integrations
media_player:
  - platform: samsungtv
    host: 192.168.1.126

hacs:
  token: !secret github_personal_access_token

mobile_app:

lovelace:
  mode: yaml
  resources:
    - url: /local/auto-entities.js
      type: module
    - url: /local/weather-card.js
      type: module
    - url: /local/layout-card.js
      type: module
    - url: /local/animated-background.js
      type: module
    - url: /local/weatherbg-card.js
      type: module
    - url: /local/card-tools.js
      type: module
    - url: /local/vasttrafik-card.js
      type: module

  # Include the Lovelace dashboard configuration from ui-lovelace.yaml
  dashboards:
    my-dashboard:
      mode: yaml
      title: Sunny's HA
      icon: mdi:home
      filename: ui-lovelace.yaml
      show_in_sidebar: true

tts:
  - platform: google_translate
    language: en
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    service_name: google_say

# Sensors
sensor:
  - platform: vasttrafik
    key: !secret vasttrafik_api_key # Store API key in secrets.yaml
    secret: !secret vasttrafik_api_secret # Store API secret in secrets.yaml
    departures:
      - name: Mot Järntorget
        from: Musikvägen
        heading: Järntorget
        lines:
          - 7
          - GRÖN
        delay: 10

  - platform: time_date
    display_options:
      - time # Current time (sensor.time)
      - date # Current date (sensor.date)

influxdb:
  host: 192.168.1.122
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influx_pass
  max_retries: 3
  default_measurement: state

# Raspberry Pi surveillance camera
camera:
  - platform: ffmpeg
    name: RasPi4
    input: rtsp://192.168.1.76:8554/unicast

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

# Template sensors
template:
  - sensor:
      - name: "Homeserver Uptime"
        unique_id: "sensor.rpi_monitor_raspberrypi.uptime"
        icon: mdi:timer-outline
        state: "{{ state_attr('sensor.rpi_monitor_raspberrypi', 'up_time') }}"
      - name: "Homeserver Used Ext Space"
        unique_id: "sensor.rpi_monitor_raspberrypi.mnt-extssd_space_prcnt"
        icon: mdi:harddisk
        unit_of_measurement: "%"
        state: "{{ state_attr('sensor.rpi_monitor_raspberrypi', 'drives')['mnt-extssd'].used_prcnt | float }}"
      - name: "Homeserver CPU 1min"
        unique_id: "sensor.rpi_monitor_raspberrypi.cpu_1min"
        icon: mdi:cpu-32-bit
        unit_of_measurement: "%"
        state: "{{ state_attr('sensor.rpi_monitor_raspberrypi', 'cpu').load_1min_prcnt | float }}"
      - name: "Homeserver Free Memory"
        unique_id: "sensor.rpi_monitor_raspberrypi.free_memory"
        icon: mdi:memory
        unit_of_measurement: "MB"
        state: "{{ state_attr('sensor.rpi_monitor_raspberrypi', 'memory').free_mb | float }}"
