animated_background:
  default_url: https://cdn.flixel.com/flixel/ypy8bw9fgw1zv2b4htp2.hd.mp4
  entity: weather.valhalla
  state_url:
    sunny:
      - /local/backgrounds/basketball.mp4
      - /local/backgrounds/gears_spin01.mp4
      - /local/backgrounds/man_running_animation.mp4
    partlycloudy:
      - /local/backgrounds/basketball.mp4
      - /local/backgrounds/enc-chest.mp4
    cloudy:
      - /local/backgrounds/Birds_Animation.mp4
      - /local/backgrounds/scifitunnel01.mp4
      - /local/backgrounds/scifitunnel03.mp4
    mostlycloudy:
      - /local/backgrounds/Chain_Animation.mp4
      - /local/backgrounds/spin_cycle.mp4
    clear-night:
      - /local/backgrounds/Count_Animation.mp4
      - /local/backgrounds/square-spin.mp4
    fog:
      - /local/backgrounds/TunnelStreak.mp4
      - /local/backgrounds/toxic_man_animation.mp4
    rainy:
      - /local/backgrounds/abstSpin03.mp4
      - /local/backgrounds/abstSpin04.mp4

title: Sunny's HA
views:
  - theme: Caule Black Coral Glass
    path: default_view
    title: Home
    badges: []
    cards:
      - type: glance
        title: Date and Time
        entities:
          - entity: sensor.time
            name: Current Time
          - entity: sensor.date
            name: Today's Date
      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.valhalla
            name: Weather in Göteborg
          - type: glance
            title: Weather Details
            entities:
              - entity: sensor.openweathermap_temperature
                name: Temperature
              - entity: sensor.openweathermap_humidity
                name: Humidity
              - entity: sensor.openweathermap_wind_speed
                name: Wind Speed
              - entity: sensor.openweathermap_pressure
                name: Pressure
      - type: entities
        title: Smart Lights
        entities:
          - entity: light.master_bedroom
            name: Bedroom
          - entity: light.hall1
            name: Living Room Light1
          - entity: light.hall2
            name: Living Room Light2
          - entity: light.dining
            name: Kitchen Dining Table
          - entity: light.entrance
            name: Entrance
      - type: "custom:vasttrafik-card"
        title: "Västrafik"
        entities:
          - sensor.musikvagen_to_goteborg_centralstation
        municipality: Göteborg
        sort: true
      - type: iframe
        url: >-
          https://embed.windy.com/embed2.html?lat=57.754459&lon=11.987620&detailLat=57.754459&detailLon=11.987620&width=650&height=450&zoom=6&level=surface&overlay=wind&product=ecmwf&menu=&message=true&marker=&calendar=24&pressure=&type=map&location=coordinates&detail=&metricWind=default&metricTemp=default&radarRange=-1
        aspect_ratio: 90%
      - type: entities
        title: Speed Test
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_ping
          - sensor.speedtest_upload
      - type: entities
        title: Server Room
        entities:
          - entity: light.supergalaxy
            name: Super Galaxy
      - type: media-control
        entity: media_player.spotify_unny
      - type: media-control
        entity: media_player.samsung_q60aa_65_tv_2
        name: Living Room TV
  - theme: Caule Black Blue
    title: Live Weather
    path: live-weather
    badges: []
    cards:
      - type: iframe
        url: https://www.youtube.com/embed/yMSc-qqW3To
        aspect_ratio: 75%
        title: Geirangerfjord cruise port, Norway
      - type: iframe
        url: https://www.youtube.com/embed/Li3Dvqlo5uE
        aspect_ratio: 75%
        title: Deutschland (Germany)
      - type: iframe
        url: https://www.youtube.com/embed/6hPWq2IG08M
        aspect_ratio: 75%
        title: Port of Helsinki, Finland
      - type: iframe
        url: https://www.youtube.com/embed/HpZAez2oYsA
        aspect_ratio: 75%
        title: Ponte delle Guglie Venice, Italy
      - type: iframe
        url: https://www.youtube.com/embed/NCfMPD5A6hQ
        aspect_ratio: 75%
        title: Stockholm, Sweden
      - type: iframe
        url: https://www.youtube.com/embed/L0PIbKJaXUQ
        aspect_ratio: 90%
        title: Reykjavik, Iceland
      - type: iframe
        url: https://www.jungfrau.ch/webcams/top-of-europe-jungfraujoch/#/video
        aspect_ratio: 75%
        title: Jungfrau, Switzerland
      - type: iframe
        url: https://www.youtube.com/embed/1phWWCgzXgM
        aspect_ratio: 75%
        title: Amsterdam, Netherlands
  - theme: Caule Black Blue
    title: House-layout
    path: house-layout
    badges: []
    cards:
      - type: picture-elements
        elements:
          - type: state-icon
            entity: light.entrance
            icon: mdi:lightbulb
            style:
              top: 70%
              left: 49%
          - type: state-icon
            entity: light.bedroom
            icon: mdi:lightbulb
            style:
              top: 78%
              left: 70%
          - type: state-icon
            entity: light.hall_sofa
            icon: mdi:lightbulb
            style:
              top: 42%
              left: 70%
          - type: state-icon
            entity: light.hall_tv
            icon: mdi:lightbulb
            style:
              top: 59%
              left: 70%
          - type: state-icon
            entity: light.kitchen_dining
            icon: mdi:lightbulb
            style:
              top: 39%
              left: 49%
          - type: state-label
            entity: media_player.emily_speaker
            style:
              top: 39%
              left: 49%
        image: /local/backgrounds/Layout-1.png
